// ADMIN LOGIN
export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const CLEAR_ADMIN_ERROR = "CLEAR_ADMIN_ERROR";
export const ADMIN_LOGOUT_REQUEST = "ADMIN_LOGOUT_REQUEST";
export const ADMIN_LOGOUT_FAIL = "ADMIN_LOGOUT_FAIL";
export const ADMIN_LOGOUT_SUCCESS = "ADMIN_LOGOUT_SUCCESS";
export const ADMIN_LOGIN_LOGOUT = "ADMIN_LOGIN_LOGOUT";
export const STAY_LOGGED_IN = 'STAY_LOGGED_IN'
export const STAY_LOGGED_OUT = 'STAY_LOGGED_OUT'


//  GET ALL MEDIA
export const GET_MEDIA_LOADING = 'GET_MEDIA_LOADING';
export const GET_MEDIA_SUCCESS = 'GET_MEDIA_SUCCESS';
export const GET_MEDIA_FAIL = 'GET_MEDIA_FAIL';
export const GET_TRAILER_MEDIA_LOADING = 'GET_TRAILER_MEDIA_LOADING';
export const GET_TRAILER_MEDIA_SUCCESS = 'GET_TRAILER_MEDIA_SUCCESS';
export const GET_TRAILER_MEDIA_FAIL = 'GET_TRAILER_MEDIA_FAIL';